# Generated by Django 5.2 on 2026-08-31 15:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runes_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='location',
        ),
        migrations.AddField(
            model_name='runestone',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Coordinates of current location', null=True, srid=4326),
        ),
    ]
