# Generated by Django 5.2 on 2026-09-18 13:31

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import gridh_abstract.models
import runes.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('published', models.BooleanField(default=True, verbose_name='published')),
                ('text', models.CharField(max_length=256, unique=True, verbose_name='general.text')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('published', models.BooleanField(default=True, verbose_name='published')),
                ('text', models.CharField(max_length=256, unique=True, verbose_name='general.text')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('published', models.BooleanField(default=True, verbose_name='published')),
                ('text', models.CharField(max_length=256, unique=True, verbose_name='general.text')),
            ],
            options={
                'verbose_name': 'Time Period',
                'verbose_name_plural': 'Time Periods',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='general.place_name')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='abstract.coordinates')),
                ('parish', models.CharField(blank=True, max_length=256, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='runes_viewer.area')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='Runestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('published', models.BooleanField(default=True, verbose_name='published')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, help_text='Descriptive text about the runestone surroundings', null=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Coordinates of current location', null=True, srid=4326)),
                ('date_visit', models.DateField(blank=True, null=True)),
                ('fornsoek_url', models.URLField(blank=True, null=True)),
                ('lantmaeteriet_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=runes.storages.IIIFFileStorage, upload_to=gridh_abstract.models.get_iiif_path, validators=[django.core.validators.validate_image_file_extension], verbose_name='iiif image')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runestones', to='runes_viewer.place')),
            ],
            options={
                'verbose_name': 'Runestone',
                'verbose_name_plural': 'Runestones',
            },
        ),
        migrations.CreateModel(
            name='RunestonePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ja', 'Ja'), ('oklart', 'Oklart'), ('möjligen', 'Möjligen'), ('nej', 'Nej')], default='ja', max_length=10)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runes_viewer.position')),
                ('runestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runes_viewer.runestone')),
            ],
        ),
        migrations.AddField(
            model_name='runestone',
            name='position',
            field=models.ManyToManyField(blank=True, help_text='Position', related_name='runestones', through='runes_viewer.RunestonePosition', to='runes_viewer.position'),
        ),
        migrations.AddField(
            model_name='runestone',
            name='time_period',
            field=models.ForeignKey(blank=True, help_text='Dating of runestone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='runes_viewer.timeperiod'),
        ),
        migrations.AddConstraint(
            model_name='runestoneposition',
            constraint=models.UniqueConstraint(fields=('runestone', 'position'), name='unique_runestone_position'),
        ),
    ]
