# Generated by Django 5.2 on 2026-09-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runes_viewer', '0002_alter_place_options_remove_place_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='abstract.created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='abstract.updated_at')),
                ('published', models.BooleanField(default=True, verbose_name='abstract.published')),
                ('firstname', models.CharField(blank=True, max_length=256, null=True)),
                ('lastname', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='parish',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='runestone',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
