# Generated by Django 5.2 on 2026-09-11 08:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runes_viewer', '0004_delete_author_alter_area_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='place',
            name='published',
        ),
        migrations.RemoveField(
            model_name='place',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='place',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='abstract.coordinates'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='general.place_name'),
        ),
        migrations.AlterField(
            model_name='runestone',
            name='position',
            field=models.ManyToManyField(blank=True, help_text='Position', to='runes_viewer.position'),
        ),
    ]
