# Generated by Django 5.2 on 2026-09-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runes_viewer', '0005_remove_place_created_at_remove_place_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runestone',
            name='location',
        ),
    ]
